name: buddyflix
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.2.5
  firebase_analytics: ^1.0.4
  cupertino_icons: ^0.1.2
  flutter_bloc: ^0.9.1
  equatable: ^0.2.0
  http: ^0.12.0+2

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "true" 
  ios: "false"
  image_path: "assets/launcher/icon.png"

flutter:
  uses-material-design: true
  assets:
   - assets/
   - secrets.json
  fonts:
   - family: Montserrat-Bold
     fonts:
      - asset: fonts/Montserrat-SemiBold.ttf
   - family: Montserrat-Light
     fonts:
      - asset: fonts/Montserrat-Light.ttf